### ISSUE TITLE
Fatal error: Class 'AjaxHelpers' not found in 

### ISSUE THREAD

**Issue by brunohauck** [mangopik/Sximo-Codeigniter#40]
Magopik I'm Having this error I'm using the older version with Ajax plugin 
I Instaled the new version and Its not working to ------ 
Fatal error: Class 'AjaxHelpers' not found in D:\xampp\htdocs\workmates\application\views\agenda\index.php on line 92

**Comment by brunohauck** [comment]
Problem solvend Installing the new version. Thanks

**Comment by mangopik** [comment]
Great
